- name: "blockinfile Test"
  hosts: 192.168.0.56
  remote_user: vagrant

  tasks:

  - name: Insertafter
    blockinfile:
      dest: /home/vagrant/block.txt
      block: |
        added after basis
        added after basis
      insertafter: "^basis"
