- name: "command to remote node"
  hosts: "{{remote_ip}}"
  remote_user: vagrant
  gather_facts: false

  tasks:
   - name: execute file
     command: python /home/vagrant/test.py
     register: result

   - debug: var=result.stdout
   
   - debug: var=result.stdout_lines

# inventory file
# 192.168.0.57 ansible_ssh_pass=vagrant

# ansible.cfg
# host_key_checking = False
