- name: "command to remote node"
  hosts: 192.168.0.56
  remote_user: vagrant
  gather_facts: yes

  tasks:
  - name: execute file
    command: python /home/vagrant/test.py
    register: result
   
  - debug: var=result

    
