- name: "command to remote node"
  hosts: all
  remote_user: "{{remote_user}}"
  gather_facts: false

  tasks:
   - name: execute file
     command: "{{command}}"
     register: result

   - debug: var=result.stdout
   
   - debug: var=result.stdout_lines

# inventory file
# 192.168.0.57 ansible_ssh_pass=vagrant

# ansible.cfg
# host_key_checking = False
