- name: "inline test"
  hosts: 192.168.0.56
  remote_user: vagrant

  tasks:
  - lineinfile:
      path: /home/vagrant/inline.txt
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^hi=', line: 'hi = 2097152' }
      - { regexp: '^iface', line: '%\tiface\t134217728' }
